### ISSUE TITLE
touchFluid not working anymore

### ISSUE THREAD

**Issue by vento17** [kamindustries/touchFluid#1]
unfortunatly that fantastic projects is not working in new Vulkan versions of td

**Comment by pucknz** [comment]
yes I've noticed this too!  ... It looks like it only one small issue involving the TexelFetchOffset in the "ComputeDivergence" shader ... the error is ... ERROR: /project1/fluid1/glslmulti2_pixel:41: 'texel offset' : argument must be compile-time constant 

I'm currently trying to solve this but have limited GLSL experience ... if anyone has any thoughts they could share that would be amazing !
<img width="1579" alt="Screenshot 2022-09-26 174538" src="https://user-images.githubusercontent.com/26964159/192195948-12478654-51c0-4e92-8bf6-956b3cf9f4eb.png">

**Comment by kamindustries** [comment]
Hey! Thanks for checking it out. Can you try this branch and see if it's fixed for you?

https://github.com/kamindustries/touchFluid/tree/texel-offset-fix

**Comment by pucknz** [comment]
Legend, thats working great ... such a great sim!
Thanks for updating it :)

Puck Murphy
+64 27 224 5094
puck.nz

**Comment by vento17** [comment]
404 page not found at the github link, please can you restore it?

**Comment by vento17** [comment]
ahhh i see you wrote it's not working anymore... sad

**Comment by kamindustries** [comment]
@vento17 I merged the changes into the main branch and deleted the branch where I was testing the fix. So try just pulling the latest from master and check it again, let me know if that works

**Comment by vento17** [comment]
Yeeeea fantastic! My fault. Work perfectly. Thanks. Thats super powerful

**Comment by kamindustries** [comment]
Great! glad to hear it
